services:
  qdrant:
    image: qdrant/qdrant:v1.17.0

    container_name: acerola-qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.vinicius-gpl.com`)"
      - "traefik.http.routers.qdrant.entrypoints=web"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
      - "traefik.http.routers.qdrant.middlewares=auth"

  rag:
    build:
      context: ..
      dockerfile: container/dockerfile
    container_name: acerola-rag
    command: python -m backend.main
    volumes:
      - ../backend/data:/app/backend/data
    env_file:
      - .env
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rag.rule=Host(`rag.vinicius-gpl.com`)"
      - "traefik.http.routers.rag.entrypoints=web"
      - "traefik.http.services.rag.loadbalancer.server.port=8000"
      - "traefik.http.routers.rag.middlewares=auth"

volumes:
  qdrant_data:

networks:
  traefik_proxy:
    external: true
